In [1]:
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import os
import cvlib as cv
import time
from flask import Flask, request, jsonify, render_template, Response


In [21]:
    model = load_model('gender_detection.model')

    # open webcam
    webcam = cv2.VideoCapture(0)
    
    classes = ['man','woman']

In [22]:
status, frame = webcam.read()
        # apply face detection

In [23]:

        face, confidence = cv.detect_face(frame)
        
        people = ""
  

        # loop through detected faces
        for idx, f in enumerate(face):

            # get corner points of face rectangle        
            (startX, startY) = f[0], f[1]
            (endX, endY) = f[2], f[3]

            # draw rectangle over face
            cv2.rectangle(frame, (startX,startY), (endX,endY), (0,255,0), 2)

            # crop the detected face region
            face_crop = np.copy(frame[startY:endY,startX:endX])

            if (face_crop.shape[0]) < 10 or (face_crop.shape[1]) < 10:
                continue

            # preprocessing for gender detection model
            face_crop = cv2.resize(face_crop, (96,96))
            face_crop = face_crop.astype("float") / 255.0
            face_crop = img_to_array(face_crop)
            face_crop = np.expand_dims(face_crop, axis=0)

            # apply gender detection on face
            conf = model.predict(face_crop)[0] # model.predict return a 2D matrix, ex: [[9.9993384e-01 7.4850512e-05]

In [26]:
face, confidence = cv.detect_face(frame)

In [27]:
face

[]

In [28]:
webcam.release()

In [7]:
print(status,' ' ,frame)

True   [[[52 68 66]
  [53 69 68]
  [50 71 67]
  ...
  [51 58 55]
  [50 60 56]
  [50 60 56]]

 [[52 68 65]
  [53 70 66]
  [55 69 66]
  ...
  [46 59 55]
  [50 60 55]
  [50 60 55]]

 [[55 69 66]
  [54 68 65]
  [56 68 63]
  ...
  [48 60 56]
  [48 60 55]
  [48 60 55]]

 ...

 [[39 55 54]
  [39 55 54]
  [39 55 54]
  ...
  [15 29 28]
  [15 29 28]
  [15 29 28]]

 [[38 56 57]
  [37 55 55]
  [37 55 54]
  ...
  [15 29 28]
  [15 29 28]
  [15 29 28]]

 [[35 55 55]
  [35 55 55]
  [37 55 54]
  ...
  [15 29 28]
  [15 29 28]
  [15 29 28]]]
